create table
  public.subscriptions (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    subscription_object jsonb not null,
    constraint subscriptions_pkey primary key (id)
  ) tablespace pg_default;